"""empty message

Revision ID: 41ef55761db3
Revises: db04d953560e
Create Date: 2021-01-24 14:25:52.065966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41ef55761db3'
down_revision = 'db04d953560e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    show = op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(show,
        [
          {
              'venue_id': 1,
              'artist_id': 1,
              'start_time': "2019-05-21T21:30:00.000Z"
          },
          {
              'venue_id': 3,
              'artist_id': 2,
              'start_time': "2019-06-15T23:00:00.000Z"
          },
          {
              'venue_id': 3,
              'artist_id': 3,
              'start_time': "2035-04-01T20:00:00.000Z"
          },
          {
              'venue_id': 3,
              'artist_id': 3,
              'start_time': "2035-04-08T20:00:00.000Z"
          },
          {
              'venue_id': 3,
              'artist_id': 3,
              'start_time': "2035-04-15T20:00:00.000Z"
          }
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Show')
    # ### end Alembic commands ###
