"""empty message

Revision ID: db04d953560e
Revises:
Create Date: 2021-01-24 11:32:55.594501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db04d953560e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    artist = op.create_table('Artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=False),
    sa.Column('genres', sa.String(length=120), nullable=False),
    sa.Column('image_link', sa.String(length=500), nullable=False),
    sa.Column('facebook_link', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=120), nullable=True),
    sa.Column('seeking_venue', sa.Boolean(), nullable=False),
    sa.Column('seeking_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(artist,
        [
          {
            "name": "Guns N Petals",
            "genres": ["Rock n Roll"],
            "city": "San Francisco",
            "state": "CA",
            "phone": "326-123-5000",
            "website": "https://www.gunsnpetalsband.com",
            "facebook_link": "https://www.facebook.com/GunsNPetals",
            "seeking_venue": True,
            "seeking_description": "Looking for shows to perform at in the San Francisco Bay Area!",
            "image_link": "https://images.unsplash.com/photo-1549213783-8284d0336c4f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=80",
          },
          {
            "name": "Matt Quevedo",
            "genres": ["Jazz"],
            "city": "New York",
            "state": "NY",
            "phone": "300-400-5000",
            "website": None,
            "facebook_link": "https://www.facebook.com/mattquevedo923251523",
            "seeking_venue": False,
            "seeking_description": None,
            "image_link": "https://images.unsplash.com/photo-1495223153807-b916f75de8c5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80",
          },
          {
            "name": "The Wild Sax Band",
            "genres": ["Jazz", "Classical"],
            "city": "San Francisco",
            "state": "CA",
            "phone": "432-325-5432",
            "website": None,
            "facebook_link": None,
            "seeking_venue": False,
            "seeking_description": None,
            "image_link": "https://images.unsplash.com/photo-1558369981-f9ca78462e61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=794&q=80",
          },
        ]
    )
    venue = op.create_table('Venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=False),
    sa.Column('image_link', sa.String(length=500), nullable=False),
    sa.Column('facebook_link', sa.String(length=120), nullable=False),
    sa.Column('website', sa.String(length=120), nullable=False),
    sa.Column('seeking_talent', sa.Boolean(), nullable=False),
    sa.Column('genres', sa.String(length=120), nullable=False),
    sa.Column('seeking_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(venue,
        [
            {
                "name": "The Musical Hop",
                "city": "San Francisco",
                "state": "CA",
                "address": "1015 Folsom Street",
                "phone": "123-123-1234",
                "image_link": "https://images.unsplash.com/photo-1543900694-133f37abaaa5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60",
                "facebook_link": "https://www.facebook.com/TheMusicalHop",
                "website": "https://www.themusicalhop.com",
                "seeking_talent": True,
                "genres": ["Jazz", "Reggae", "Swing", "Classical", "Folk"],
                "seeking_description": "We are on the lookout for a local artist to play every two weeks. Please call us."
            },
            {
                "name": "The Dueling Pianos Bar",
                "city": "New York",
                "state": "NY",
                "address": "335 Delancey Street",
                "phone": "914-003-1132",
                "image_link": "https://images.unsplash.com/photo-1497032205916-ac775f0649ae?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80",
                "facebook_link": "https://www.facebook.com/theduelingpianos",
                "website": "https://www.theduelingpianos.com",
                "seeking_talent": False,
                "genres": ["Classical", "R&B", "Hip-Hop"],
                "seeking_description": None
            },
            {
                "name": "Park Square Live Music & Coffee",
                "city": "San Francisco",
                "state": "CA",
                "address": "34 Whiskey Moore Ave",
                "phone": "415-000-1234",
                "image_link": "https://images.unsplash.com/photo-1485686531765-ba63b07845a7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=747&q=80",
                "facebook_link": "https://www.facebook.com/ParkSquareLiveMusicAndCoffee",
                "website": "https://www.parksquarelivemusicandcoffee.com",
                "seeking_talent": False,
                "genres": ["Rock n Roll", "Jazz", "Classical", "Folk"],
                "seeking_description": None
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Venue')
    op.drop_table('Artist')
    # ### end Alembic commands ###
